export default function Head() {
    return (
      <>
        <title>69 내전기록실</title>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=1024" />
        <meta name="description" content="Generated by create next app" />
        <meta name="theme-color" content="#000000" />
        <link rel="icon" href="/favicon.ico" />
      </>
    );
  }
  