import { Geist, Geist_Mono } from "next/font/google";
import ViewportFixer from './ViewportFixer'; // 경로에 맞게 수정
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "69 내전기록실",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ViewportFixer /> {/* 💥 모든 페이지에서 강제 적용 */}
        {children}
      </body>
    </html>
  );
}

